---
- include:              '../tasks/create_files.yml'
- include:              '../tasks/install_packages.yml'
- include:              '../tasks/unpack_tarballs.yml'
- include:              '../tasks/scripts.yml'
- include:              '../tasks/commands.yml'
- include:              '../tasks/install_files.yml'
