---
install_packages:
  - 'tor'
install_files:
  - owner:              'root'
    group:              'root'
    mode:               '0644'
    src:                '../../../sensitive/ansible/roles/tor/files/conf/torrc'
    dest:               '/etc/tor/torrc'
  - owner:              'root'
    group:              'root'
    mode:               '0644'
    src:                "{{ role_path }}/files/conf/front_page.html"
    dest:               '/etc/tor/front_page.html'
restart_services:
  - 'tor'
enable_services:
  - 'tor'
start_services:
  - 'tor'
