---
dependencies:
  - role:       'user_friendly'
    when:       skipdeps is not defined
  - role:       'automatic_updates'
    when:       skipdeps is not defined
  - role:       'sshd'
    when:       skipdeps is not defined
  - role:       'monitored'
    when:       skipdeps is not defined
  - role:       'nethack'
    when:       skipdeps is not defined
