---
dependencies:
  - role:       'user_friendly'
    when:       skipdeps is not defined
  - role:       'automatic_updates'
    when:       skipdeps is not defined
  - role:       'sshd'
    when:       skipdeps is not defined
  - role:       'tor'
    when:       skipdeps is not defined
  - role:       'dns_external'
    when:       skipdeps is not defined
