---
dependencies:
  - role:       'user_friendly'
    when:       skipdeps is not defined
  - role:       'root_keys'
    when:       skipdeps is not defined
  - role:       'automatic_updates'
    when:       skipdeps is not defined
  - role:       'sshd'
    when:       skipdeps is not defined
  - role:       'reboot'
    when:       skipdeps is not defined
  - role:       'pi'
    when:       skipdeps is not defined
  - role:       'dhcpd'
    when:       skipdeps is not defined
  - role:       'cryptkeeper'
    when:       skipdeps is not defined
  - role:       'static_address'
    when:       skipdeps is not defined
  - role:       'tftp'
    when:       skipdeps is not defined
  - role:       'nethack'
    when:       skipdeps is not defined
  - role:       'temper-python'
    when:       skipdeps is not defined
  - role:       'debian-netboot'
    when:       skipdeps is not defined
  - role:       'pictures'
    when:       skipdeps is not defined
  - role:       'https-private'
    when:       skipdeps is not defined
  - role:       'front_page'
    when:       skipdeps is not defined
  - role:       'wiki'
    when:       skipdeps is not defined
  - role:       'remote_proxy'
    when:       skipdeps is not defined
  - role:       'transmission_proxy'
    when:       skipdeps is not defined
  - role:       'monitored'
    when:       skipdeps is not defined
  - role:       'dns_internal'
    when:       skipdeps is not defined
  - role:       'crl_server'
    when:       skipdeps is not defined
