---
dependencies:
  - role:       'user_friendly'
    when:       skipdeps is not defined
  - role:       'root_keys'
    when:       skipdeps is not defined
  - role:       'automatic_updates'
    when:       skipdeps is not defined
  - role:       'sshd'
    when:       skipdeps is not defined
  - role:       'reboot'
    when:       skipdeps is not defined
  - role:       'pi'
    when:       skipdeps is not defined
  - role:       'krb5'
    when:       skipdeps is not defined
  - role:       'nagios'
    when:       skipdeps is not defined
  - role:       'smokeping'
    when:       skipdeps is not defined
# zabbix isn't ready yet
#  - role: 'zabbix'
  - role:       'escrow'
    when:       skipdeps is not defined
  - role:       'dphys-swapfile'
    when:       skipdeps is not defined
  - role:       'monitored'
    when:       skipdeps is not defined
