---
install_files:
  - owner:              'root'
    group:              'root'
    mode:               '0644'
    src:                "{{ role_path }}/../../../ssl/ca/intermediate/cert.pem"
    dest:               '/etc/ssl/certs/Aaron_Intermediate_CA.pem'
  - owner:              'root'
    group:              'root'
    mode:               '0644'
    src:                "{{ role_path }}/../../../ssl/hosts/{{ inventory_hostname }}/cert.pem"
    dest:               "/etc/ssl/certs/{{ inventory_hostname }}.pem"
  - owner:              'root'
    group:              'root'
    mode:               '0644'
    src:                "{{ role_path }}/../../../ssl/hosts/{{ inventory_hostname }}/chain.pem"
    dest:               "/etc/ssl/certs/chain.pem"
  - owner:              'root'
    group:              'root'
    mode:               '0640'
    src:                "{{ role_path }}/../../../../sensitive/ssl/hosts/{{ inventory_hostname }}/key.pem"
    dest:               "/etc/ssl/private/{{ inventory_hostname }}.pem"

