---
- include:              '../tasks/install_packages.yml'
- include:              '../tasks/remove_packages.yml'
- include:              '../tasks/create_files.yml'
- include:              '../tasks/install_files.yml'
- include:              '../tasks/template_files.yml'
- include:              '../tasks/initialize_files.yml'
- include:              '../tasks/enable_services.yml'
- include:              '../tasks/start_services.yml'
- include:              '../tasks/restart_services.yml'
  when:                 install_files_result.changed
                        or template_files_result.changed
