---
dependencies:
  - role:       'reboot'
    when:       skipdeps is not defined
  - role:       'no_systemd'
    when:       skipdeps is not defined
  - role:       'user_friendly'
    when:       skipdeps is not defined
  - role:       'time'
    when:       skipdeps is not defined
  - role:       'sshd'
    when:       skipdeps is not defined
  - role:       'root_keys'
    when:       skipdeps is not defined
  - role:       'monitored'
    when:       skipdeps is not defined
  - role:       'pi'
    when:       skipdeps is not defined
  - role:       'storage_server'
    when:       skipdeps is not defined
  - role:       'file_server'
    when:       skipdeps is not defined
  - role:       'transmission'
    when:       skipdeps is not defined
  - role:       'flexget'
    when:       skipdeps is not defined
